src/main/resources/db/migration/V1__init.sql
DB
초기 DB 셋팅
DB 내 테이블 생성
resolved : #12
=> db: 초기 DB 셋팅

build.gradle, src/main/java/com/health/yogiodigym/config/JasyptConfig.java, src/main/resources/application.yml, src/test/resources/application.yml
프로젝트 세팅
<br/>
- Jasypt 라이브러리를 사용해서 yml파일에 포함되는 민감한 내용을 암호화.
- `application-prod.yml`, `application-dev.yml`이 생성될 경우 암호화 필요.
<br/>
https://www.devglan.com/online-tools/jasypt-online-encryption-decryption
1. 암호화할 문자열 입력
2. **Two Way Encryption** 선택
3. 키 입력후 **Encrypt** 버튼 선택
4. `application.yml`에 `ENC()` 안에 암호화된 문자열 입력
<br/>
Ex)
```yaml
spring:
datasource:
url: ENC(KLD++NYRIy20iq/7dW5Uag==)
```
<br/>
우측 상단의 'Edit Configuration' 선택
<br/>
`application.ym`l의 `jasypt.encryptor.password`에 기입한 `${JASYPT_KEY}`에 맞게 환경변수명을 'JASYPT_KEY'로 설정 후 키 값을 입력해주고 실행합니다.
<br/>
테스트 또한 환경변수를 입력하고 실행시켜 완료되는지 확인합니다.
테스트 코드는 test폴더를 우클릭 후 `Run Test in ''` 버튼을 선택해 실행시킬 수 있습니다.
<br/>
📌 만약 로컬 컴퓨터에 환경변수를 지정하신 경우 인텔리제이에 입력하지 않으셔도 됩니다.
<br/>
녹색으로 완료표시가 뜨면 정상 실행 완료.
<br/>
터미널에 `./gradlew clean build`를 실행해 빌드가 정상적으로 완료되는지 …
=> chore: Jasypt 설정

Dockerfile
CI/CD
- DEV 브랜치 push -> 테스트 서버로 배포
- MAIN 브랜치 push -> 운영 서버로 배포
1. 프로젝트를 도커이미지로 빌드
2. 도커이미지를 도커 허브로 push
3. 테스트/운영 서버로 ssh 접속
4. 도커 이미지 pull
5. 테스트 서버일 경우 기존 컨테이너 종료 및 삭제 후 새 컨테이너 생성
6. 운영서버일 경우 도커 스웜 서비스 업데이트
=> CI/CD: Dockerfile 추가

.github/workflows/cicd.yml, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
CI/CD
- DEV 브랜치 push -> 테스트 서버로 배포
- MAIN 브랜치 push -> 운영 서버로 배포
1. 프로젝트를 도커이미지로 빌드
2. 도커이미지를 도커 허브로 push
3. 테스트/운영 서버로 ssh 접속
4. 도커 이미지 pull
5. 테스트 서버일 경우 기존 컨테이너 종료 및 삭제 후 새 컨테이너 생성
6. 운영서버일 경우 도커 스웜 서비스 업데이트
resolved: #33
=> CI/CD: Github Actions 스크립트 수정

Dockerfile
CI/CD
- DEV 브랜치 push -> 테스트 서버로 배포
- MAIN 브랜치 push -> 운영 서버로 배포
1. 프로젝트를 도커이미지로 빌드
2. 도커이미지를 도커 허브로 push
3. 테스트/운영 서버로 ssh 접속
4. 도커 이미지 pull
5. 테스트 서버일 경우 기존 컨테이너 종료 및 삭제 후 새 컨테이너 생성
6. 운영서버일 경우 도커 스웜 서비스 업데이트
resolved: #33
=> CI/CD: Dockerfile 수정

src/main/java/com/health/yogiodigym/member/auth/MemberStatus.java, src/main/java/com/health/yogiodigym/member/auth/Role.java, src/main/java/com/health/yogiodigym/member/entity/Member.java, src/main/java/com/health/yogiodigym/member/repository/MemberRepository.java, src/main/resources/db/migration/V3__create_authority.sql
DB, Entity
- 회원 테이블 권한 컬럼 삭제
- 권한 테이블 생성
- 회원 상태, 권한 Enum 추가
- 회원 엔티티 추가
- 회원 레포지토리 추가
Member DB 연동
resolved: #37
=> chore: 회원 도메인 추가

src/main/java/com/health/yogiodigym/common/exception/CustomException.java, src/main/java/com/health/yogiodigym/common/exception/GlobalExceptionHandler.java, src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java, src/main/java/com/health/yogiodigym/common/message/SuccessMessage.java, src/main/java/com/health/yogiodigym/common/response/HttpResponse.java
공통 클래스 생성
<br/>
- 응답 성공/실패 메시지 클래스 생성
- Rest Api의 예외 처리를 위한 추상 클래스 생성
- Rest Api의 응답을 위한 클래스 생성
<br/>
```java
public class MemberNotFoundException extends CustomException {  // CustomException 상속
@Override
public HttpStatus getStatus() {
return HttpStatus.BAD_REQUEST;  // status 지정
}
@Override
public String getMessage() {
return ErrorMessage.MEMBER_NOT_FOUND.getMessage();  // 메시지 enum 클래스의 메시지 불러오기
}
}
```
```java
@Service
public class MemberServiceImpl implements MemberService {
// ...
public void getMemberDetail() {
Member member = memberRepository.findByMemberId(memberId)
.orElseThrow(() -> new MemberNotFoundException());   // 사용자 정의 예외 던짐
// ...
}
}
```
- 사용자 정의 클래스를 던지게 되면 `ExceptionHandler`에서 처리하고 클라이언트에게 응답해줍니다.
- 사용자 정의 클래스의 패키지 경로는 정해야 할 것 같습니다.
(common.exception 패키지에 모두 넣을지, 혹은 …
=> feat: 공통으로 사용되는 표준 클래스 생성

src/main/java/com/health/yogiodigym/chat/service/ChatRoomService.java, src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java
버그 수정
- 채팅방 생성 서비스 로직 수정
`LessonService`에서 생성된 ChatRoom을 사용해 강의 저장
resolved: #65
=> bug: 채팅방 생성 서비스 로직 수정

src/main/resources/db/migration/V4__create_chat.sql, src/main/resources/templates/admin.html
- V4 : lesson_id 컬럼 삭제
- 강의 삭제 정상 실행여부 Test
- admin.html 세분화
x
강의 삭제 정상 작동
feat#32
=> feat: 관리자 강의 삭제 및 UI 업데이

.github/workflows/cicd.yml
cicd 명령어 수정
- auth 프로파일 포함해 실행하도록 수정
resolved: #74
=> cicd: 도커 실행 명령어 수정

src/main/java/com/health/yogiodigym/member/entity/MemberOAuth2User.java, src/main/java/com/health/yogiodigym/member/service/impl/MemberServiceImpl.java, src/main/java/com/health/yogiodigym/member/service/impl/NCPStorageServiceImpl.java
회원
로그인 사진수정 비밀번호수정 오류 수정 
resolved: #100
=> bug: 로그인 버그 수정

src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
레디스, 카프카 설정 변경
레디스, 카프카 설정 변경
#109
=> chore: 레디스, 카프카 설정 변경

src/main/java/com/health/yogiodigym/board/dto/BoardDto.java, src/main/java/com/health/yogiodigym/board/repository/BoardRepository.java, src/main/java/com/health/yogiodigym/board/service/BoardService.java, src/main/java/com/health/yogiodigym/board/service/impl/BoardServiceImpl.java, src/main/java/com/health/yogiodigym/chat/dto/ChatRoomDto.java, src/main/java/com/health/yogiodigym/chat/entity/ChatParticipant.java, src/main/java/com/health/yogiodigym/chat/service/impl/ChatMessageServiceImpl.java, src/main/java/com/health/yogiodigym/chat/service/impl/ChatRoomServiceImpl.java, src/main/java/com/health/yogiodigym/member/controller/view/MainViewController.java, src/main/resources/templates/chat/chat.html, src/test/java/com/health/yogiodigym/chat/service/ChatRoomServiceTest.java, src/test/java/com/health/yogiodigym/chat/service/impl/ChatMessageServiceTest.java
대시보드 기능 구현
- Top10 인기게시글 조회 기능 구현
- 로그인한 사용자의 채팅방 목록 조회 기능 구현 (읽지 않은 메시지 수 포함)
resolved: #87
=> feat: 대시보드 인기게시글, 채팅방 목록 조회 기능 구현

src/main/resources/static/css/chat/chat.css, src/main/resources/templates/chat/chat.html
채팅
채팅 화면 수정
- Nav 바 추가
- 사이드 바 추가
resolved: #127
=> refactor: 채팅 화면 수정

src/main/java/com/health/yogiodigym/lesson/repository/LessonEnrollmentRepository.java, src/main/java/com/health/yogiodigym/lesson/repository/LessonRepository.java, src/main/java/com/health/yogiodigym/lesson/service/impl/LessonEnrollmentServiceImpl.java, src/main/java/com/health/yogiodigym/lesson/service/impl/LessonServiceImpl.java, src/main/java/com/health/yogiodigym/my/controller/rest/MyController.java, src/main/resources/templates/my/lesson.html
내 강의 검색 버그 수정
내 강의 검색 버그 수정
내 강의 페이지 접근 시 내가 만든 강의와 신청한 강의가 모두 보임
resolved: #140
=> bug: 내 강의 검색 버그 수정

src/main/java/com/health/yogiodigym/admin/service/impl/AdminMemberToMasterServiceImpl.java, src/main/java/com/health/yogiodigym/common/exception/PasswordEmptyException.java, src/main/java/com/health/yogiodigym/common/message/ErrorMessage.java, src/main/java/com/health/yogiodigym/member/entity/Member.java, src/main/java/com/health/yogiodigym/member/repository/MemberRepository.java, src/main/java/com/health/yogiodigym/member/service/impl/MemberServiceImpl.java, src/main/java/com/health/yogiodigym/my/controller/rest/MyController.java, src/main/java/com/health/yogiodigym/my/entity/MemberToMaster.java, src/main/java/com/health/yogiodigym/my/repository/MemberToMasterRepository.java
회원가입
회원가입 시 회원 엔티티 생성을 코드를 회원엔티티 내부 메소드에서 처리하게 변경
resolved: #143
=> refactor: 회원가입 코드컨벤션 맞춰서 리펙터링

src/main/resources/static/js/calendar/filter_action.js, src/main/resources/templates/calendar/select_exercise.html, src/main/resources/templates/calendar/select_food.html
캘린더
-이벤트 색상설정 방법 변경
-데이터 검색리스트 css 변경
=> refactor : 캘린더 UI 2차 변경

src/main/resources/static/js/calendar/filter_action.js
---
name: Pull Request Template
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''
---
=> fix : 색상, alert 메세지 변경

src/main/java/com/health/yogiodigym/member/service/impl/MemberServiceImpl.java, src/main/resources/templates/gym/gyms.html, src/main/resources/templates/member/find_pwd.html
없음
코드 컨벤션에 맞춰서 수정
resolved: #162
=> refactor: 컨벤션에 맞춰서 리펙터링

src/main/resources/templates/gym/gyms.html
헬스장 찾기
헬스장 찾기 게시물 번호 넘버링 오류 수정
resolved: #165
=> bug: 헬스창 찾기 페이징 넘버링 오류 수정
